package com.phoenix.audit;

public enum AuditAction {
    LOGIN_SUCCESS, LOGIN_FAILED,
    REGISTER_OTP_REQUESTED, REGISTER_OTP_FAILED, REGISTER_COMPLETED,
    PASSWORD_RESET_REQUESTED, PASSWORD_RESET_FAILED, PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED, PASSWORD_CHANGE_FAILED,
    USER_CREATED, USER_UPDATED, USER_DEACTIVATED, USER_VIEWED, USERS_LISTED,
    PRODUCT_CREATED, PRODUCT_UPDATED, PRODUCT_DELETED,
    DEALER_CREATED, DEALER_UPDATED, DEALER_DELETED,
    AUDIT_LOG_VIEWED, ACCESS_DENIED
}
